//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FalloutPNP_PipBoy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FalloutPNP_PipBoy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmorClass.
        /// </summary>
        internal static string sArmorClass {
            get {
                return ResourceManager.GetString("sArmorClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTEMPTS LEFT: .
        /// </summary>
        internal static string sAttempts {
            get {
                return ResourceManager.GetString("sAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string sCategory {
            get {
                return ResourceManager.GetString("sCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x{0} {1}.
        /// </summary>
        internal static string sCodeString {
            get {
                return ResourceManager.GetString("sCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectricDamageResistance.
        /// </summary>
        internal static string sElectroDamageResistance {
            get {
                return ResourceManager.GetString("sElectroDamageResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectricDamageThreshold.
        /// </summary>
        internal static string sElectroDamageThreshold {
            get {
                return ResourceManager.GetString("sElectroDamageThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REICO INDUSTRIES (TM) TERMLINK PROTOCOL.
        /// </summary>
        internal static string sHeader1 {
            get {
                return ResourceManager.GetString("sHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER PASSWORD NOW.
        /// </summary>
        internal static string sHeader2 {
            get {
                return ResourceManager.GetString("sHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaserDamageResistance.
        /// </summary>
        internal static string sLaserDamageResistance {
            get {
                return ResourceManager.GetString("sLaserDamageResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaserDamageThreshold.
        /// </summary>
        internal static string sLaserDamageThreshold {
            get {
                return ResourceManager.GetString("sLaserDamageThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNOPQRSTUVWXYZ.
        /// </summary>
        internal static string sLetters {
            get {
                return ResourceManager.GetString("sLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string sName {
            get {
                return ResourceManager.GetString("sName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NormalDamageResistance.
        /// </summary>
        internal static string sNormalDamageResistance {
            get {
                return ResourceManager.GetString("sNormalDamageResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NormalDamageThreshold.
        /// </summary>
        internal static string sNormalDamageThreshold {
            get {
                return ResourceManager.GetString("sNormalDamageThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !@#$%^&amp;*()-=_+[]{};&apos;\:&quot;|,./&lt;&gt;?.
        /// </summary>
        internal static string sSymbols {
            get {
                return ResourceManager.GetString("sSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string sWpnDmg {
            get {
                return ResourceManager.GetString("sWpnDmg", resourceCulture);
            }
        }
    }
}
